In [3]:
from computer_vision.main import poster_analysis
from audio.main import audiofy
import pandas as pd

In [5]:
bechdel_df = pd.read_json("audio/bechdel_data.json")
imdb_df = pd.read_json("audio/tmdb_data.json")
imdb_df["imdb_id"] = imdb_df["imdb_id"].apply(lambda x: x[2:])
merged_df = pd.merge(
    bechdel_df, imdb_df, left_on="imdbid", right_on="imdb_id"
).sample(20)

In [6]:
df = poster_analysis(merged_df)

100%|██████████| 20/20 [02:06<00:00,  6.34s/it]

In [7]:
df

,year,title_x,imdbid,id_x,rating,adult,backdrop_path,belongs_to_collection,budget,genres,...,tagline,title_y,video,vote_average,vote_count,imdb_id,nb_women,nb_men,area_women,area_men
4116,1995,Dolores Claiborne,0109642,2394,3,False,/9vJ57nbL4hWJrmsyjKTxiGXqrBU.jpg,None,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",...,"Sometimes, an accident can be an unhappy woman...",Dolores Claiborne,False,7.2,553,0109642,1,1,0.152320,0.136901
7807,1966,A Big Hand for the Little Lady,0060165,2696,1,False,/4kMhrn6zR4FNrLJ67eY4b93cRdC.jpg,None,0,"[{'id': 37, 'name': 'Western'}]",...,All the action you can take...all the adventur...,A Big Hand for the Little Lady,False,7.0,50,0060165,1,2,0.006192,0.012344
5585,2011,Apart,1525552,4242,3,False,None,None,0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",...,Damned Together. Condemned By Fate.,Apart,False,4.0,11,1525552,0,2,0.000000,0.014264
3366,2015,Sunset Song,2262161,6928,3,False,/oMvovUVMe7HIvPsZxq23cBdLwZB.jpg,None,0,"[{'id': 18, 'name': 'Drama'}]",...,"An epic story of love, loss and the land that ...",Sunset Song,False,6.3,80,2262161,1,0,0.008101,0.000000
3247,1985,Agnes of God,0088683,602,3,False,/OAxqslLEzlBF8eT8KcfO4EqQko.jpg,None,0,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",...,"That night, murder wasn't the only sin.",Agnes of God,False,6.3,92,0088683,0,1,0.000000,0.141664
1654,1989,Leningrad Cowboys Go America,0097728,4646,0,False,/kevyDBlyEJvQOPGd0b3BbtPKqrK.jpg,"{'id': 187736, 'name': 'Leningrad Cowboys Coll...",0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",...,,Leningrad Cowboys Go America,False,7.0,108,0097728,0,5,0.000000,0.148176
2045,2005,Elizabethtown,0368709,8908,3,False,/cx2nwab4wKPpmQ9uacgBU7jJfEp.jpg,None,57000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",...,It's a heck of a place to find yourself,Elizabethtown,False,6.2,907,0368709,1,1,0.009045,0.010155
2465,2013,White Lies,2386257,8629,3,False,None,None,0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",...,,White Lies,False,5.8,4,2386257,0,0,0.000000,0.000000
5297,2001,Elvira&#39;s Haunted Hills,0265171,4403,3,False,/yVGbzNoKaeicVkl2ilqmEzr7MYh.jpg,"{'id': 182617, 'name': 'Elvira Collection', 'p...",1500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...",...,,Elvira's Haunted Hills,False,5.4,76,0265171,1,0,0.018549,0.000000
806,2001,Sweet November,0230838,8533,1,False,/lDtmwXg6nknzViEQ5SDkk4D1WEZ.jpg,None,40000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",...,She Just Needed A Month To Change His Life For...,Sweet November,False,6.9,1052,0230838,1,2,0.164736,0.288083
5393,2010,"Wolfman, The",0780653,717,1,False,/juIHQJjA9ByHQcG63Hy5eJbVMbc.jpg,None,150000000,"[{'id': 27, 'name': 'Horror'}, {'id': 36, 'nam...",...,When the moon is full the legend comes to life,The Wolfman,False,5.8,1586,0780653,0,0,0.000000,0.000000
1994,2013,Riley Rewind,2944454,4953,3,False,None,None,0,"[{'id': 14, 'name': 'Fantasy'}]",...,,Riley Rewind,False,6.8,13,2944454,0,0,0.000000,0.000000
4479,2021,"French Dispatch, The",8847712,10115,3,False,/u4Vm8n0suBYimsUoarqMw5vxNU8.jpg,None,25000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",...,,The French Dispatch,False,7.2,1343,8847712,0,4,0.000000,0.001888
2922,2013,Kill Your Darlings,1311071,5362,1,False,/lkQ5ZZsCrQ1S7TOzujXM2Ct7NvZ.jpg,None,1030064,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",...,A true story of obsession and murder.,Kill Your Darlings,False,7.1,1165,1311071,0,2,0.000000,0.360363
2774,1969,Support Your Local Sheriff!,0065051,1100,1,False,/nWe91B0iGdOc12cGB7Pks4HiKId.jpg,None,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 37, 'nam...",...,Bad men... Bad ladies... Bad horses...,Support Your Local Sheriff!,False,7.0,126,0065051,0,1,0.000000,0.069021
7821,2002,Tuck Everlasting,0283084,1529,3,False,/5u3UyWBGbTBV6yzt13Ahj9AbS45.jpg,None,15000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",...,"If you could choose to live forever, would you?",Tuck Everlasting,False,6.6,382,0283084,1,3,0.077083,0.107925
4172,1966,Cathy Come Home,0059020,2855,3,False,None,None,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10770, 'n...",...,,Cathy Come Home,False,7.1,20,0059020,1,2,0.002613,0.007096
6783,2021,"Kissing Booth 3, The",12783454,10050,3,False,/oOZM1C3wZtsZtdidVgEazeas7U4.jpg,"{'id': 726619, 'name': 'The Kissing Booth Coll...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",...,The end of an era. The beginning of everything...,The Kissing Booth 3,False,7.2,1369,12783454,1,2,0.016704,0.036608
160,1985,Weird Science,0090305,520,3,False,/7386slmhA9YqwU2Fbi9X1sIQsPx.jpg,None,7500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",...,"If you can't get a date, make one!",Weird Science,False,6.5,1065,0090305,2,1,0.025136,0.009901
5665,2010,Steam of Life,1583323,2337,0,False,None,None,580000,"[{'id': 99, 'name': 'Documentary'}]",...,,Steam of Life,False,7.1,28,1583323,0,3,0.000000,0.017755

In [8]:
df1 = audiofy(df)

In [9]:
df1

,year,title_x,imdbid,id_x,rating,adult,backdrop_path,belongs_to_collection,budget,genres,...,video,vote_average,vote_count,imdb_id,nb_women,nb_men,area_women,area_men,imdb_id,ratio
4116,1995,Dolores Claiborne,0109642,2394,3,False,/9vJ57nbL4hWJrmsyjKTxiGXqrBU.jpg,None,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",...,False,7.2,553,0109642,1,1,0.152320,0.136901,imdb_id 0109642 imdb_id 0109642 Name: 41...,0.000000
7807,1966,A Big Hand for the Little Lady,0060165,2696,1,False,/4kMhrn6zR4FNrLJ67eY4b93cRdC.jpg,None,0,"[{'id': 37, 'name': 'Western'}]",...,False,7.0,50,0060165,1,2,0.006192,0.012344,imdb_id 0060165 imdb_id 0060165 Name: 78...,0.000000
5585,2011,Apart,1525552,4242,3,False,None,None,0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",...,False,4.0,11,1525552,0,2,0.000000,0.014264,imdb_id 1525552 imdb_id 1525552 Name: 55...,1.591871
3366,2015,Sunset Song,2262161,6928,3,False,/oMvovUVMe7HIvPsZxq23cBdLwZB.jpg,None,0,"[{'id': 18, 'name': 'Drama'}]",...,False,6.3,80,2262161,1,0,0.008101,0.000000,imdb_id 2262161 imdb_id 2262161 Name: 33...,0.627178
3247,1985,Agnes of God,0088683,602,3,False,/OAxqslLEzlBF8eT8KcfO4EqQko.jpg,None,0,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",...,False,6.3,92,0088683,0,1,0.000000,0.141664,imdb_id 0088683 imdb_id 0088683 Name: 32...,0.289136
1654,1989,Leningrad Cowboys Go America,0097728,4646,0,False,/kevyDBlyEJvQOPGd0b3BbtPKqrK.jpg,"{'id': 187736, 'name': 'Leningrad Cowboys Coll...",0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",...,False,7.0,108,0097728,0,5,0.000000,0.148176,imdb_id 0097728 imdb_id 0097728 Name: 16...,0.000000
2045,2005,Elizabethtown,0368709,8908,3,False,/cx2nwab4wKPpmQ9uacgBU7jJfEp.jpg,None,57000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",...,False,6.2,907,0368709,1,1,0.009045,0.010155,imdb_id 0368709 imdb_id 0368709 Name: 20...,1.117808
2465,2013,White Lies,2386257,8629,3,False,None,None,0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",...,False,5.8,4,2386257,0,0,0.000000,0.000000,imdb_id 2386257 imdb_id 2386257 Name: 24...,7.651613
5297,2001,Elvira&#39;s Haunted Hills,0265171,4403,3,False,/yVGbzNoKaeicVkl2ilqmEzr7MYh.jpg,"{'id': 182617, 'name': 'Elvira Collection', 'p...",1500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...",...,False,5.4,76,0265171,1,0,0.018549,0.000000,imdb_id 0265171 imdb_id 0265171 Name: 52...,0.789016
806,2001,Sweet November,0230838,8533,1,False,/lDtmwXg6nknzViEQ5SDkk4D1WEZ.jpg,None,40000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",...,False,6.9,1052,0230838,1,2,0.164736,0.288083,imdb_id 0230838 imdb_id 0230838 Name: 80...,0.842197
5393,2010,"Wolfman, The",0780653,717,1,False,/juIHQJjA9ByHQcG63Hy5eJbVMbc.jpg,None,150000000,"[{'id': 27, 'name': 'Horror'}, {'id': 36, 'nam...",...,False,5.8,1586,0780653,0,0,0.000000,0.000000,imdb_id 0780653 imdb_id 0780653 Name: 53...,0.149215
1994,2013,Riley Rewind,2944454,4953,3,False,None,None,0,"[{'id': 14, 'name': 'Fantasy'}]",...,False,6.8,13,2944454,0,0,0.000000,0.000000,imdb_id 2944454 imdb_id 2944454 Name: 19...,0.341530
4479,2021,"French Dispatch, The",8847712,10115,3,False,/u4Vm8n0suBYimsUoarqMw5vxNU8.jpg,None,25000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",...,False,7.2,1343,8847712,0,4,0.000000,0.001888,imdb_id 8847712 imdb_id 8847712 Name: 44...,0.608291
2922,2013,Kill Your Darlings,1311071,5362,1,False,/lkQ5ZZsCrQ1S7TOzujXM2Ct7NvZ.jpg,None,1030064,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",...,False,7.1,1165,1311071,0,2,0.000000,0.360363,imdb_id 1311071 imdb_id 1311071 Name: 29...,0.314246
2774,1969,Support Your Local Sheriff!,0065051,1100,1,False,/nWe91B0iGdOc12cGB7Pks4HiKId.jpg,None,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 37, 'nam...",...,False,7.0,126,0065051,0,1,0.000000,0.069021,imdb_id 0065051 imdb_id 0065051 Name: 27...,0.000000
7821,2002,Tuck Everlasting,0283084,1529,3,False,/5u3UyWBGbTBV6yzt13Ahj9AbS45.jpg,None,15000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",...,False,6.6,382,0283084,1,3,0.077083,0.107925,imdb_id 0283084 imdb_id 0283084 Name: 78...,0.000000
4172,1966,Cathy Come Home,0059020,2855,3,False,None,None,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10770, 'n...",...,False,7.1,20,0059020,1,2,0.002613,0.007096,imdb_id 0059020 imdb_id 0059020 Name: 41...,0.188907
6783,2021,"Kissing Booth 3, The",12783454,10050,3,False,/oOZM1C3wZtsZtdidVgEazeas7U4.jpg,"{'id': 726619, 'name': 'The Kissing Booth Coll...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",...,False,7.2,1369,12783454,1,2,0.016704,0.036608,imdb_id 12783454 imdb_id 12783454 Name: ...,2.447939
160,1985,Weird Science,0090305,520,3,False,/7386slmhA9YqwU2Fbi9X1sIQsPx.jpg,None,7500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",...,False,6.5,1065,0090305,2,1,0.025136,0.009901,imdb_id 0090305 imdb_id 0090305 Name: 16...,0.350692
5665,2010,Steam of Life,1583323,2337,0,False,None,None,580000,"[{'id': 99, 'name': 'Documentary'}]",...,False,7.1,28,1583323,0,3,0.000000,0.017755,imdb_id 1583323 imdb_id 1583323 Name: 56...,0.551865

In [10]:
df1.to_csv('dataset_turfu')